### ISSUE TITLE
response with many [/INST]

### ISSUE THREAD

**Issue by ken-xu-e** [bentoml/OpenLLM#515]
hi friend，
            why I run the LLM with command openllm start llama --model-id NousResearch/llama-2-13b-hf
     the error as below， could you please help me？

(base) ubuntu@VM-48-13-ubuntu:~$ export OPENLLM_ENDPOINT=http://localhost:3000
(base) ubuntu@VM-48-13-ubuntu:~$ openllm query 'What are large language models?'
[/INST]

[/INST]

[/INST]

[/INST]

[/INST]

[/INST]

[/INST]

[/INST]

[/INST]

[/INST]

**Comment by p208p2002** [comment]
To interact with LM you must using the *-chat or *-insturction version and follow it's template.
for example, you can not interact with llama-2 directly but llama-2-chat, and while chatting with llama-2-chat you have to follow the template.
> ref: https://github.com/facebookresearch/llama#fine-tuned-chat-models

command `$ openllm start llama` follow the llama-chat's template, if the model don't follow the template will cause the error that you display, i think it's normally. 
> for any non-chat model, try use `$ openllm start opt`, due to it only do text-complete without any template.

But maybe we can using custom template? I don't see any about custom template in document yet. Also `$ openllm start SOM_MODEL` may make a little confuse, is that could be better like `$ openllm start chat` for llama-chat like model ,`$ openllm start text-complete` for base causal LM?

**Comment by aarnphm** [comment]
There is no way for us to determine whether it is a chat model or not. For now, users will need to be responsible for formatting the prompt themselves when sending request to `/v1/generate`, `/v1/generate_stream`

We do support chat/conversation prompt through OpenAI compatible endpoint, `/v1/chat/completions`

We decided to keep the base generation endpoint not to do any special things so that users have full control of what to format the prompt with.
